export const userActionTypes = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGNOUT: "SIGNOUT",

  GET_USER_PROFILE_DATA_START: "GET_USER_PROFILE_DATA_START",
  GET_USER_PROFILE_DATA_SUCCESS: "GET_USER_PROFILE_DATA_SUCCESS",
  GET_USER_PROFILE_DATA_FAILURE: "GET_USER_PROFILE_DATA_SUCCESS",
};
