export const postActionTypes = {
  FETCH_POSTS: "FETCH_POSTS",
  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  LIKE_POST: "LIKE_POST",
};
